---
title: "Monte Carlo Progam"
author: "Ze Zheng"
date: "2/18/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Ze Zheng

#Monte Carlo Simulation

library(tidyverse)
library(stargazer)
library(urca)

u1 <- rnorm(5000,0,1)
u2 <- rnorm(5000,0,2)
v1 <- u1
v2 <- u2

t<-(1:5000)

#Random Walk  1
for (i in 2:5000) v1[i]<-v1[i-1]+u1[i] 

#Random Walk  2

for (i in 2:5000) v2[i]<-v2[i-1]+u2[i] 
ggplot()+
  geom_line(aes(x=t,y=v1),col="white")+
  geom_line(aes(x=t,y=v2),col="pink")+
  theme_dark()+
  geom_vline(xintercept = 500,color="yellow")


# Random Walk 1 and Random Walk 2 Regression (w1~w2)
reg1<-lm(v1~v2)

# Stargazer Regression Result
stargazer(reg1, report="vcs", type="text",
          omit.stat = c("ser", "f"),
          ci=TRUE, omit.table.layout = "n")
summary(reg1)
sum= summary(reg1)
#Generating f-stats
fstat<-sum$fstatistic
fstat # value, numf, dendf find from fstats

# f-stats only for value
fstat<-sum$fstatistic["value"]
fstat

fstat<-sum$r.squared
fstat # R^2
fstat<-sum$adj.r.squared
fstat # adjusted R^2


```


```{r}
#Clears environment so that previous code does not conflict with new code
rm(list=ls())

# Taken From Applied Econometrics 
#Econ 508 - Fall 2014
#from UIUC 
#Monte Carlo
set.seed(2000)
r <- 1000
n <- 100
A <- array(0,c(1,1000))
rsq<-numeric(r) # a spot to save R-squared

#The Loop
for(i in 1:r){
    u<-rnorm(n) 
    v<-rnorm(n) 
    y<-rep(0,n) 
    x<-rep(0,n) 
    for(j in 2:n){ 
      x[j] <- x[j-1] + u[j]  
      y[j] <- y[j-1] + v[j] 
    }
    A[1,i] <- round(summary(lm(y~x))$coef["x","t value"],2)
}


#Generate the number of rejections out of 100 simulations
B<-as.matrix(abs(A)>abs(qt(0.05,n-1)))  
apply(B,1,sum)

reg2<-(lm(y~x))
rsq[j]<-summary(reg2)$r.squared

# The result
reg2<-(lm(y~x))
stargazer(reg2, report="vcs", type="text",
          omit.stat = c("ser", "f"),
          ci=TRUE, omit.table.layout = "n")


#Summary of the regression and fstats
sum=summary(reg2)

#Generate Fstats
fstat<-sum$fstatistic
fstat # value, numf, dendf find from fstats

rej<-ifelse(rsq >= 0.05,1,0)# If R^2 is greater or = 0.05 (True of False)
summary(rej)


```
